version: '3.9'
services:
  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - pgdata:/var/lib/postgresql/data
  nestapp:
    container_name: nestapp
    image: incrementor-nest:1.0.0
    env_file: .env
    build: .
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
volumes:
  pgdata: {}
